### ISSUE TITLE
Video unavailable!

### ISSUE THREAD

**Issue by ghost** [facebookresearch/ActivityNet-Entities#5]
Hi, 

I have been running into an issue recently. The videos should be accessible via Youtube and the video keys provided in the dataset; For example, the video corresponding to the key "v_UhNgPK81r" should exist in the following link: "youtu.be/v_UhNgPK81r".
However, recently I have been getting the "unavailable" message whenever I try to open this link. Do you have any idea what might be wrong with the links/videos?

Regards,
Ali

**Comment by LuoweiZhou** [comment]
@aligholami First, make sure you have the right video id (remind that we prepended `v_` to all the 11-char youtube ids and you need to remove that when downloading videos). If the video is no longer available on YouTube, please contact the ActivityNet maintainer ([Frost](mailto:mengmeng.xu@kaust.edu.sa)) for the missing videos.
