### ISSUE TITLE
segment start and end time

### ISSUE THREAD

**Issue by cs2r** [facebookresearch/ActivityNet-Entities#7]
I am trying to understand this dataset how it is annotated but I can't find how the videos are divided into segments and how to find the start and the end time of each segment on each video.

**Comment by LuoweiZhou** [comment]
@cs2r The temporal segments come from the original ActivityNet Captions (except for the hidden test set). You can find the duration and segment timestamps info in the [GVD](https://github.com/facebookresearch/grounded-video-description#data-preparation) repo (download [link](https://dl.fbaipublicfiles.com/ActivityNet-Entities/ActivityNet-Entities/anet_entities_captions.tar.gz) to the captions). You will find `anet_captions_all_splits.json` to be what you need.

**Comment by LuoweiZhou** [comment]
@cs2r I've added video duration and segment timestamp info to the annotation files: https://github.com/facebookresearch/ActivityNet-Entities/commit/26d96a25c2b72d19aab000044391ac7ebf556a6e

I will remove the dependency on `anet_captions_all_splits.json` in GVD as well.

**Comment by cs2r** [comment]
Many thx Mr @LuoweiZhou for your help.
